[package]
name = "tucupi"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Eufrasio <lucaseufrasio@gmail.com>"]
description = "A concurrent dependency checker and upgrader with built-in security auditing."
repository = "https://github.com/lucaseufrasio/tucupi"


[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "process", "fs", "io-util"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.120"
reqwest = { version = "0.13.4", features = ["json"] }
toml = "0.8.19"
anyhow = "1.0.86"
semver = "1.0.23"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
